services:
  postgres:
    image: postgres:17
    container_name: finance-app-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_USER: root
      POSTGRES_DB: finance-app
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
